var PZLNAME = {
	/* 日本語のパズル名 */
	ja : {
		aho        : 'アホになり切れ',
		amibo      : 'あみぼー',
		ayeheya    : '∀人∃ＨＥＹＡ',
		bag        : 'バッグ',
		barns      : 'バーンズ',
		bdblock    : 'ボーダーブロック',
		bonsan     : 'ぼんさん/へやぼん',
		bosanowa   : 'ボサノワ',
		box        : 'ボックス',
		cbblock    : 'コンビブロック',
		chocona    : 'チョコナ',
		cojun      : 'コージュン',
		country    : 'カントリーロード',
		creek      : 'クリーク',
		factors    : '因子の部屋',
		fillmat    : 'フィルマット',
		fillomino  : 'フィルオミノ',
		firefly    : 'ホタルビーム',
		fivecells  : 'ファイブセルズ',
		fourcells  : 'フォーセルズ',
		goishi     : '碁石ひろい',
		gokigen    : 'ごきげんななめ',
		hakoiri    : 'はこいり○△□',
		hanare     : 'はなれ組',
		hashikake  : '橋をかけろ',
		heyawake   : 'へやわけ',
		hitori     : 'ひとりにしてくれ',
		icebarn    : 'アイスバーン',
		icelom     : 'アイスローム',
		icelom2    : 'アイスローム２',
		ichimaga   : 'イチマガ',
		ichimagam  : '磁石イチマガ',
		ichimagax  : '一回曲がって交差もするの',
		kaero      : 'お家に帰ろう',
		kakuro     : 'カックロ',
		kakuru     : 'カックル',
		kinkonkan  : 'キンコンカン',
		kouchoku   : '交差は直角に限る',
		kramma     : '快刀乱麻',
		kurochute  : 'クロシュート',
		kurodoko   : '黒どこ(黒マスはどこだ)',
		kusabi     : 'クサビリンク',
		lightup    : '美術館',
		lits       : 'ＬＩＴＳ',
		loopsp     : '環状線スペシャル',
		loute      : 'エルート',
		mashu      : 'ましゅ',
		mejilink   : 'メジリンク',
		minarism   : 'マイナリズム',
		mochikoro  : 'モチコロ',
		mochinyoro : 'モチにょろ',
		nagenawa   : 'なげなわ',
		nanro      : 'ナンロー',
		nawabari   : 'なわばり',
		norinori   : 'のりのり',
		numlin     : 'ナンバーリンク',
		nuribou    : 'ぬりぼう',
		nurikabe   : 'ぬりかべ',
		paintarea  : 'ペイントエリア',
		pipelink   : 'パイプリンク',
		reflect    : 'リフレクトリンク',
		renban     : '連番窓口',
		ringring   : 'リングリング',
		ripple     : '波及効果',
		roma       : 'ろーま',
		sashigane  : 'さしがね',
		shakashaka : 'シャカシャカ',
		shikaku    : '四角に切れ',
		shimaguni  : '島国',
		shugaku    : '修学旅行の夜',
		shwolf     : 'ヤギとオオカミ',
		slalom     : 'スラローム',
		slither    : 'スリザーリンク',
		snakes     : 'へびいちご',
		sudoku     : '数独',
		sukoro     : '数コロ',
		sukororoom : '数コロ部屋',
		tasquare   : 'たすくえあ',
		tatamibari : 'タタミバリ',
		tateyoko   : 'タテボーヨコボー',
		tawa       : 'たわむれんが',
		tentaisho  : '天体ショー',
		tilepaint  : 'タイルペイント',
		toichika   : '遠い誓い',
		triplace   : 'トリプレイス',
		usotatami  : 'ウソタタミ',
		view       : 'ヴィウ',
		wagiri     : 'ごきげんななめ・輪切',
		wblink     : 'シロクロリンク',
		yajikazu   : 'やじさんかずさん',
		yajirin    : 'ヤジリン'
	},
	/* 英語のパズル名 */
	en : {
		aho        : 'Aho-ni-Narikire',
		amibo      : 'Amibo',
		ayeheya    : 'ekawayeh',
		bag        : 'BAG (Corral)',
		barns      : 'Barns',
		bdblock    : 'Border Block',
		bonsan     : 'Bonsan/Heya-Bon',
		bosanowa   : 'Bosanowa',
		box        : 'Box',
		cbblock    : 'Combi Block',
		chocona    : 'Chocona',
		cojun      : 'Cojun',
		country    : 'Country Road',
		creek      : 'Creek',
		factors    : 'Rooms of Factors',
		fillmat    : 'Fillmat',
		fillomino  : 'Fillomino',
		firefly    : 'Hotaru Beam (Glow of Fireflies)',
		fivecells  : 'FiveCells',
		fourcells  : 'FourCells',
		goishi     : 'Goishi',
		gokigen    : 'Gokigen-naname',
		hakoiri    : 'Triplets',
		hanare     : 'Hanare-gumi',
		hashikake  : 'Bridges',
		heyawake   : 'Heyawake',
		hitori     : 'Hitori',
		icebarn    : 'Icebarn',
		icelom     : 'Icelom',
		icelom2    : 'Icelom2',
		ichimaga   : 'Ichimaga',
		ichimagam  : 'Crossing Ichimaga',
		ichimagax  : 'Magnetic Ichimaga',
		kaero      : 'Return Home',
		kakuro     : 'Kakuro',
		kakuru     : 'Kakuru',
		kinkonkan  : 'Kin-Kon-Kan',
		kouchoku   : 'Kouchoku',
		kramma     : 'KaitoRamma',
		kurochute  : 'Kurochute',
		kurodoko   : 'Kurodoko',
		kusabi     : 'Kusabi',
		lightup    : 'Akari (Light Up)',
		lits       : 'LITS',
		loopsp     : 'Loop Special',
		loute      : 'L-route',
		mashu      : 'Masyu (Pearl Puzzle)',
		mejilink   : 'Mejilink',
		minarism   : 'Minarism',
		mochikoro  : 'Mochikoro',
		mochinyoro : 'Mochinyoro',
		nagenawa   : 'Nagenawa',
		nanro      : 'Nanro',
		nawabari   : 'Territory',
		norinori   : 'Norinori',
		numlin     : 'Numberlink',
		nuribou    : 'Nuribou',
		nurikabe   : 'Nurikabe',
		paintarea  : 'Paintarea',
		pipelink   : 'Pipelink',
		reflect    : 'Reflect Link',
		renban     : 'Renban-Madoguchi',
		ringring   : 'Ring-ring',
		ripple     : 'Ripple Effect',
		roma       : 'Roma',
		sashigane  : 'Sashigane',
		shakashaka : 'ShakaShaka',
		shikaku    : 'Shikaku',
		shimaguni  : 'Islands',
		shugaku    : 'School Trip',
		shwolf     : 'Sheeps and Wolves',
		slalom     : 'Slalom',
		slither    : 'Slitherlink',
		snakes     : 'Hebi-Ichigo',
		sudoku     : 'Sudoku',
		sukoro     : 'Sukoro',
		sukororoom : 'Sukoro-room',
		tasquare   : 'Tasquare',
		tatamibari : 'Tatamibari',
		tateyoko   : 'Tatebo-Yokobo',
		tawa       : 'Tawamurenga',
		tentaisho  : 'Tentaisho',
		tilepaint  : 'Tilepaint',
		toichika   : 'Toichika',
		triplace   : 'Tri-place',
		usotatami  : 'Uso-tatami',
		view       : 'View',
		wagiri     : 'Gokigen-naname:wagiri',
		wblink     : 'Shirokuro-link',
		yajikazu   : 'Yajisan-Kazusan',
		yajirin    : 'Yajilin'
	},
	/* 別名 */
	alias : {
		fillomino : { kanpen2:'fillomino01'},
		hashikake : { kanpen:'hashi'},
		lightup   : { url:'akari', kanpen:'bijutsukan'},
		mashu     : { kanpen:'masyu'},
		numlin    : { kanpen:'numberlink'},
		ripple    : { kanpen:'hakyukoka'},
		slither   : { kanpen:'slitherlink'},
		yajirin   : { url:'yajilin', kanpen:'yajilin'}
	},
	/* 関数 */
	exists : function(name){ return !!this.toPID(name);},
	toPID : function(name){
		if(!!this.ja[name]){ return name;}
		for(var pid in this.alias){
			if(!this.alias[pid]){ continue;}
			for(var type in this.alias[pid]){
				if(this.alias[pid][type]===name){ return pid;}
			}
		}
		return '';
	},
	toURLID : function(pid){
		return (!!this.alias[pid] && !!this.alias[pid].url ? this.alias[pid].url : pid);
	},
	toKanpen : function(pid){
		return (!!this.alias[pid] && !!this.alias[pid].kanpen ? this.alias[pid].kanpen : pid);
	}
};
