
/* concat前のテスト用スクリプト */

(function(){
	var dir = (function getpath(){
		var srcs=document.getElementsByTagName('script');
		for(var i=0;i<srcs.length;i++){
			var result = srcs[i].src.match(/^(.*\/)pzprv3-all\.js$/);
			if(result){ return result[1] + (!result[1].match(/\/$/) ? '/' : '');}
		}
		return "";
	})();

	var files = [
		"lib/candle.js",
		"pzpr/CoreClass.js",
		"pzpr/Puzzle.js",
		"pzpr/BoardPiece.js",
		"pzpr/Board.js",
		"pzpr/BoardExec.js",
		"pzpr/LineManager.js",
		"pzpr/AreaManager.js",
		"pzpr/Graphic.js",
		"pzpr/MouseInput.js",
		"pzpr/KeyInput.js",
		"pzpr/URL.js",
		"pzpr/Encode.js",
		"pzpr/FileData.js",
		"pzpr/Answer.js",
		"pzpr/Operation.js",
		"puzzle-common/Graphic.js",
		"puzzle-common/KeyInput.js",
		"puzzle-common/MouseInput.js",
		"puzzle-common/Answer.js",
		"puzzle-common/BoardExec.js",
		"puzzle-common/Encode.js",
		"puzzle-common/FileData.js",
		"ui/Boot.js",
		"ui/UI.js",
		"ui/Menu.js",
		"ui/MenuArea.js",
		"ui/PopupMenu.js",
		"ui/ToolArea.js",
		"ui/KeyPopup.js",
		"ui/DataBase.js",
		"ui/Timer.js",
		"ui/Debug.js",
		"puzzle/amibo.js",
		"puzzle/bag.js",
		"puzzle/barns.js",
		"puzzle/bdblock.js",
		"puzzle/bonsan.js",
		"puzzle/bosanowa.js",
		"puzzle/box.js",
		"puzzle/cbblock.js",
		"puzzle/country.js",
		"puzzle/creek.js",
		"puzzle/factors.js",
		"puzzle/fillmat.js",
		"puzzle/fillomino.js",
		"puzzle/firefly.js",
		"puzzle/goishi.js",
		"puzzle/gokigen.js",
		"puzzle/hakoiri.js",
		"puzzle/hanare.js",
		"puzzle/hashikake.js",
		"puzzle/heyawake.js",
		"puzzle/hitori.js",
		"puzzle/icebarn.js",
		"puzzle/ichimaga.js",
		"puzzle/kaero.js",
		"puzzle/kakuro.js",
		"puzzle/kakuru.js",
		"puzzle/kinkonkan.js",
		"puzzle/kouchoku.js",
		"puzzle/kramma.js",
		"puzzle/kurochute.js",
		"puzzle/kurodoko.js",
		"puzzle/kurotto.js",
		"puzzle/kusabi.js",
		"puzzle/lightup.js",
		"puzzle/lits.js",
		"puzzle/lookair.js",
		"puzzle/loopsp.js",
		"puzzle/loute.js",
		"puzzle/mashu.js",
		"puzzle/mejilink.js",
		"puzzle/minarism.js",
		"puzzle/nagenawa.js",
		"puzzle/nanro.js",
		"puzzle/nawabari.js",
		"puzzle/numlin.js",
		"puzzle/nurikabe.js",
		"puzzle/paintarea.js",
		"puzzle/pipelink.js",
		"puzzle/reflect.js",
		"puzzle/renban.js",
		"puzzle/ripple.js",
		"puzzle/roma.js",
		"puzzle/shakashaka.js",
		"puzzle/shikaku.js",
		"puzzle/shimaguni.js",
		"puzzle/shugaku.js",
		"puzzle/slalom.js",
		"puzzle/slither.js",
		"puzzle/snakes.js",
		"puzzle/sudoku.js",
		"puzzle/sukoro.js",
		"puzzle/tasquare.js",
		"puzzle/tatamibari.js",
		"puzzle/tateyoko.js",
		"puzzle/tawa.js",
		"puzzle/tentaisho.js",
		"puzzle/tilepaint.js",
		"puzzle/toichika.js",
		"puzzle/triplace.js",
		"puzzle/wblink.js",
		"puzzle/yajikazu.js",
		"puzzle/yajirin.js",
		"puzzle/yajitatami.js",
		"puzzle/yosenabe.js"
	];
	for(var i=0;i<files.length;i++){
		document.write('<script type="text/javascript" src="'+dir+files[i]+'"></script>');
	}
})();
