var pzprv3={version:"v3.4.0pre"};
document.writeln('<script type="text/javascript" src="../candle/source/candle.core.js"></script>');
document.writeln('<script type="text/javascript" src="../candle/source/candle.base.js"></script>');
document.writeln('<script type="text/javascript" src="../candle/source/candle.svg.js"></script>');
document.writeln('<script type="text/javascript" src="../candle/source/candle.canvas.js"></script>');
document.writeln('<script type="text/javascript" src="../candle/source/candle.sl.js"></script>');
document.writeln('<script type="text/javascript" src="../candle/source/candle.vml.js"></script>');

document.writeln("<script type=\"text/javascript\" src=\"src/pzprBase/CoreClass.js\"></script>");
document.writeln("<script type=\"text/javascript\" src=\"src/pzprBase/Main.js\"></script>");
document.writeln("<script type=\"text/javascript\" src=\"src/pzprBase/Timer.js\"></script>");
document.writeln("<script type=\"text/javascript\" src=\"src/pzprBase/BoardPiece.js\"></script>");
document.writeln("<script type=\"text/javascript\" src=\"src/pzprBase/Board.js\"></script>");
document.writeln("<script type=\"text/javascript\" src=\"src/pzprBase/BoardExt.js\"></script>");
document.writeln("<script type=\"text/javascript\" src=\"src/pzprBase/Graphic.js\"></script>");
document.writeln("<script type=\"text/javascript\" src=\"src/pzprBase/MouseInput.js\"></script>");
document.writeln("<script type=\"text/javascript\" src=\"src/pzprBase/KeyInput.js\"></script>");
document.writeln("<script type=\"text/javascript\" src=\"src/pzprBase/Encode.js\"></script>");
document.writeln("<script type=\"text/javascript\" src=\"src/pzprBase/Filesys.js\"></script>");
document.writeln("<script type=\"text/javascript\" src=\"src/pzprBase/DataBase.js\"></script>");
document.writeln("<script type=\"text/javascript\" src=\"src/pzprBase/Answer.js\"></script>");
document.writeln("<script type=\"text/javascript\" src=\"src/pzprBase/Undo.js\"></script>");
document.writeln("<script type=\"text/javascript\" src=\"src/pzprBase/Menu.js\"></script>");
